 const selectNationnality =[
    {value: "Afghanistan", label: "Afghanistan"},
    {value: "Albania", label: "Albania"},
    {value: "Algeria", label: "Algeria"},
    {value: "American Samoa", label: "American Samoa"},
    {value: "Andorra", label: "Andorra"},
    {value: "Angola", label: "Angola"},
    {value: "Anguilla", label: "Anguilla"},
    {value: "Antarctica", label: "Antarctica"},
    {value: "Antigua and Barbuda", label: "Antigua and Barbuda"},
    {value: "Argentina", label: "Argentina"},
    {value: "Armenia", label: "Armenia"},
    {value: "Aruba", label: "Aruba"},
    {value: "Australia", label: "Australia"},
    {value: "Austria", label: "Austria"},
    {value: "Azerbaijan", label: "Azerbaijan"},
    {value: "Bahamas", label: "Bahamas"},
    {value: "Bahrain", label: "Bahrain"},
    {value: "Bangladesh", label: "Bangladesh"},
    {value: "Barbados", label: "Barbados"},
    {value: "Belarus", label: "Belarus"},
    {value: "Belgium", label: "Belgium"},
    {value: "Belize", label: "Belize"},
    {value: "Benin", label: "Benin"},
    {value: "Bermuda", label: "Bermuda"},
    {value: "Bhutan", label: "Bhutan"},
    {value: "Bolivia", label: "Bolivia"},
    {value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina"},
    {value: "Botswana", label: "Botswana"},
    {value: "Bouvet Island", label: "Bouvet Island"},
    {value: "Brazil", label: "Brazil"},
    {value: "British Indian Ocean Territory", label: "British Indian Ocean Territory"},
    {value: "Brunei Darussalam", label: "Brunei Darussalam"},
    {value: "Bulgaria", label: "Bulgaria"},
    { value: "Morocco", label: "Morocco"},
    {value: "Burkina Faso", label: "Burkina Faso"},
    {value: "Burundi", label: "Burundi"},
    {value: "Cambodia", label: "Cambodia"},
    {value: "Cameroon", label: "Cameroon"},
    {value: "Canada", label: "Canada"},
    {value: "Cape Verde", label: "Cape Verde"},
    {value: "Cayman Islands", label: "Cayman Islands"},
    {value: "Central African Republic", label: "Central African Republic"},
    {value: "Chad", label: "Chad"},
    {value: "Chile", label: "Chile"},
    {value: "China", label: "China"},
    {value: "Christmas Island", label: "Christmas Island"},
    {value: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands"},
    {value: "Colombia", label: "Colombia"},
    {value: "Comoros", label: "Comoros"},
    {value: "Congo", label: "Congo"},
    {value: "Congo, the Democratic Republic of the", label: "Congo, the Democratic Republic of the"},
    {value: "Cook Islands", label: "Cook Islands"},
    {value: "Costa Rica", label: "Costa Rica"},
    {value: "Cote d'Ivoire", label: "Cote d'Ivoire"},
    {value: "Croatia (Hrvatska)", label: "Croatia (Hrvatska)"},
    {value: "Cuba", label: "Cuba"},
    {value: "Cyprus", label: "Cyprus"},
    {value: "Czech Republic", label: "Czech Republic"},
    {value: "Denmark", label: "Denmark"},
    {value: "Djibouti", label: "Djibouti"},
    {value: "Dominica", label: "Dominica"},
    {value: "Dominican Republic", label: "Dominican Republic"},
    {value: "East Timor", label: "East Timor"},
    {value: "Ecuador", label: "Ecuador"},
    {value: "Egypt", label: "Egypt"},
    { value: "El Salvador", label: "El Salvador" },
    { value: "Equatorial Guinea", label: "Equatorial Guinea" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estonia", label: "Estonia" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Falkland Islands", label: "Falkland Islands (Malvinas)" },
    { value: "Faroe Islands", label: "Faroe Islands" },
    { value: "Fiji", label: "Fiji" },
    { value: "Finland", label: "Finland" },
    { value: "France", label: "France" },
    { value: "France Metropolitan", label: "France, Metropolitan" },
    { value: "French Guiana", label: "French Guiana" },
    { value: "French Polynesia", label: "French Polynesia" },
    { value: "French Southern Territories", label: "French Southern Territories" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Germany", label: "Germany" },
    { value: "Ghana", label: "Ghana" },
    { value: "Gibraltar", label: "Gibraltar" },
    { value: "Greece", label: "Greece" },
    { value: "Greenland", label: "Greenland" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guadeloupe", label: "Guadeloupe" },
    { value: "Guam", label: "Guam" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
   
]
    
export default selectNationnality